// src/pages/TemplateConfigurationPage/TemplateConfigurationPage.tsx
import React, { useState, useEffect } from 'react';
import {
    Box,
    Card,
    CardContent,
    FormControl,
    InputLabel,
    Select,
    MenuItem,
    Button,
    Typography,
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableRow,
    TextField,
    Chip,
    Alert,
    CircularProgress,
    Container,
    Stepper,
    Step,
    StepLabel,
    Grid,
    Paper
} from '@mui/material';
import { Download, Upload, Save, Settings, OpenInNew, Add } from '@mui/icons-material';
import { useConfigurationContext } from '../../contexts/ConfigurationContext';
import { templateApiService } from '../../services/api/templateApi';
import { sourceSystemApiService } from '../../services/api/sourceSystemApi';
import { templateSourceMappingApiService } from '../../services/api/templateSourceMappingApi';
import { FileTypeTemplate, FieldTemplate, FieldMappingConfig, TemplateToConfigurationResult } from '../../types/template';
import { SourceSystemInfo, SourceSystemWithUsage, TemplateSourceMappingRequest, FieldMapping } from '../../types/sourceSystem';
import { useNavigate } from 'react-router-dom';
import { AddSourceSystemModal } from '../../components/AddSourceSystemModal/AddSourceSystemModal';

const steps = ['Select Template', 'Configure Mappings', 'Generate & Save'];

export const TemplateConfigurationPage: React.FC = () => {
    const [activeStep, setActiveStep] = useState(0);
    const [fileTypes, setFileTypes] = useState<FileTypeTemplate[]>([]);
    const [selectedFileType, setSelectedFileType] = useState('');
    const [transactionTypes, setTransactionTypes] = useState<string[]>([]);
    const [selectedTransactionType, setSelectedTransactionType] = useState('');
    const [templateFields, setTemplateFields] = useState<FieldTemplate[]>([]);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [templateJobName, setTemplateJobName] = useState('');
    const [success, setSuccess] = useState<string | null>(null);
    const [generatedConfig, setGeneratedConfig] = useState<any>(null);
    
    // US002: Source System Management state
    const [availableSourceSystems, setAvailableSourceSystems] = useState<SourceSystemWithUsage[]>([]);
    const [selectedSourceSystemId, setSelectedSourceSystemId] = useState('');
    const [selectedSourceSystemName, setSelectedSourceSystemName] = useState('');
    const [showAddSourceSystemModal, setShowAddSourceSystemModal] = useState(false);
    const [loadingSourceSystems, setLoadingSourceSystems] = useState(false);

    const navigate = useNavigate();

    const {
        selectedSourceSystem,
        selectedJob,
        saveConfiguration
    } = useConfigurationContext();

    // Load file types and source systems on mount
    useEffect(() => {
        fetchFileTypes();
        fetchSourceSystems();
    }, []);

    // Load transaction types when file type changes
    useEffect(() => {
        if (selectedFileType) {
            fetchTransactionTypes(selectedFileType);
        }
    }, [selectedFileType]);

    // Load template fields when both are selected
    useEffect(() => {
        if (selectedFileType && selectedTransactionType) {
            fetchTemplateFields(selectedFileType, selectedTransactionType);
            fetchSourceSystemsWithUsage(selectedFileType, selectedTransactionType);
            setActiveStep(1);
        }
    }, [selectedFileType, selectedTransactionType]);

    // Auto-generate job name when template and source system selection changes
    useEffect(() => {
        if (selectedFileType && selectedTransactionType && selectedSourceSystemId) {
            const autoGeneratedJobName = `${selectedFileType.toLowerCase()}_${selectedSourceSystemId.toLowerCase()}_${selectedTransactionType.toLowerCase()}_job`;
            setTemplateJobName(autoGeneratedJobName);
            console.log('Auto-generated job name:', autoGeneratedJobName);
        } else {
            setTemplateJobName('');
        }
    }, [selectedFileType, selectedTransactionType, selectedSourceSystemId]);

    const fetchFileTypes = async () => {
        try {
            setLoading(true);
            const types = await templateApiService.getFileTypes();
            setFileTypes(
                types.map((t: any) => ({
                    ...t,
                    recordLength: t.recordLength ?? 0
                }))
            );
        } catch (error) {
            setError('Failed to load file types');
        } finally {
            setLoading(false);
        }
    };

    const fetchTransactionTypes = async (fileType: string) => {
        try {
            const data = await templateApiService.getTransactionTypes(fileType);
            setTransactionTypes(data);
            if (data.length === 1) {
                setSelectedTransactionType(data[0]);
            }
        } catch (error) {
            console.error('Error fetching transaction types:', error);
        }
    };

    const fetchTemplateFields = async (fileType: string, transactionType: string) => {
        setLoading(true);
        try {
            const data = await templateApiService.getTemplateFields(fileType, transactionType);
            setTemplateFields(data);
            setError(null);
        } catch (error) {
            setError('Failed to load template fields');
            console.error('Error fetching template fields:', error);
        } finally {
            setLoading(false);
        }
    };

    // US002: Source System Management functions
    const fetchSourceSystems = async () => {
        setLoadingSourceSystems(true);
        try {
            const data = await sourceSystemApiService.getAllSourceSystems();
            console.log('Fetched source systems:', data);
            // Convert to SourceSystemWithUsage format
            const systemsWithUsage = data.map(system => ({
                id: system.id,
                name: system.name,
                type: system.type,
                description: system.description,
                enabled: system.enabled,
                jobCount: system.jobCount,
                createdDate: system.createdDate,
                hasExistingConfiguration: false,
                existingJobName: '',
                lastConfigured: undefined,
                templateCount: 0
            }));
            setAvailableSourceSystems(systemsWithUsage);
        } catch (error) {
            console.error('Error fetching source systems:', error);
            setError('Failed to load source systems');
        } finally {
            setLoadingSourceSystems(false);
        }
    };

    const fetchSourceSystemsWithUsage = async (fileType: string, transactionType: string) => {
        setLoadingSourceSystems(true);
        try {
            const data = await sourceSystemApiService.getSourceSystemsWithUsage(fileType, transactionType);
            console.log('Fetched source systems with usage:', data);
            setAvailableSourceSystems(data);
        } catch (error) {
            console.error('Error fetching source systems with usage:', error);
            // Fallback to basic source systems if usage fetch fails
            await fetchSourceSystems();
        } finally {
            setLoadingSourceSystems(false);
        }
    };

    const handleSourceFieldChange = (fieldIndex: number, sourceField: string) => {
        const updated = [...templateFields];
        updated[fieldIndex].sourceField = sourceField;
        setTemplateFields(updated);
    };

    const handleTransformationChange = (fieldIndex: number, transformationType: string) => {
        const updated = [...templateFields];
        updated[fieldIndex].transformationType = transformationType as any;
        setTemplateFields(updated);
    };

    // US002: Source System Management handlers
    const handleSourceSystemChange = (event: any) => {
        const systemId = event.target.value;
        setSelectedSourceSystemId(systemId);
        
        const selectedSystem = availableSourceSystems.find(sys => sys.id === systemId);
        setSelectedSourceSystemName(selectedSystem?.name || '');
        
        console.log('Selected source system:', systemId, selectedSystem?.name);
    };

    const handleNewSourceSystemCreated = (newSystem: SourceSystemInfo) => {
        console.log('New source system created:', newSystem);
        // Add to available systems list
        const newSystemWithUsage = {
            id: newSystem.id,
            name: newSystem.name,
            type: newSystem.type,
            description: newSystem.description,
            enabled: newSystem.enabled,
            jobCount: newSystem.jobCount,
            createdDate: newSystem.createdDate,
            hasExistingConfiguration: false,
            existingJobName: '',
            lastConfigured: undefined,
            templateCount: 0
        };
        setAvailableSourceSystems(prev => [...prev, newSystemWithUsage]);
        
        // Auto-select the newly created system
        setSelectedSourceSystemId(newSystem.id);
        setSelectedSourceSystemName(newSystem.name);
        
        // Show success message
        setSuccess(`Source system "${newSystem.name}" created successfully!`);
    };

    const generateConfiguration = async () => {
        // Validation checks
        if (!selectedFileType) {
            setError('Please select a file type');
            return;
        }

        if (!selectedTransactionType) {
            setError('Please select a transaction type');
            return;
        }

        if (!selectedSourceSystemId) {
            setError('Please select a source system');
            return;
        }

        const jobName = templateJobName || (selectedJob?.name || selectedJob?.jobName);
        if (!jobName) {
            setError('Please ensure a job name is available');
            return;
        }

        try {
            setLoading(true);
            setError(null);

            console.log('🚀 Starting configuration generation...', {
                fileType: selectedFileType,
                transactionType: selectedTransactionType,
                sourceSystem: selectedSourceSystemId,
                jobName: jobName
            });

            // Step 1: Generate configuration from template
            let configWithMetadata;

            try {
                configWithMetadata = await templateApiService.createConfigurationFromTemplateWithMetadata(
                    selectedFileType,
                    selectedTransactionType,
                    selectedSourceSystemId,
                    jobName
                );

                console.log('✅ Template configuration generated:', configWithMetadata);
            } catch (templateError) {
                console.error('❌ Template generation failed:', templateError);
                const errorMsg = templateError instanceof Error ? templateError.message : 'Unknown error';
                throw new Error(`Failed to generate template configuration: ${errorMsg}`);
            }

            // Step 2: Merge user customizations from the UI
            const enhancedFields = configWithMetadata.fields.map((fieldMapping: any, index: number) => {
                const userCustomization = templateFields[index];

                return {
                    ...fieldMapping,
                    sourceField: userCustomization?.sourceField || fieldMapping.sourceField || '',
                    transformationType: userCustomization?.transformationType || fieldMapping.transformationType || 'source'
                };
            });

            const finalConfiguration = {
                ...configWithMetadata,
                fields: enhancedFields
            };

            console.log('✅ Final configuration prepared:', finalConfiguration);
            setGeneratedConfig(finalConfiguration);

            // Step 3: Enhanced save with template-source mappings
            try {
                console.log('🔄 Saving template configuration and field mappings...');
                
                // Step 3A: Save batch configuration (existing functionality)
                const configForBackend = {
                    sourceSystem: finalConfiguration.sourceSystem,
                    jobName: finalConfiguration.jobName,
                    transactionType: finalConfiguration.transactionType,
                    description: finalConfiguration.description || `Generated from ${selectedFileType}/${selectedTransactionType} template`,
                    fieldMappings: finalConfiguration.fields.map((field: any) => ({
                        fieldName: field.fieldName,
                        sourceField: field.sourceField || '',
                        targetField: field.targetField,
                        targetPosition: field.targetPosition,
                        length: field.length,
                        dataType: field.dataType,
                        transformationType: field.transformationType,
                        transactionType: field.transactionType || finalConfiguration.transactionType,
                        value: field.value,
                        defaultValue: field.defaultValue,
                        format: field.format
                    })),
                    createdBy: 'template-user',
                    version: 1
                };

                console.log('📦 Saving batch configuration:', configForBackend);
                
                const batchResponse = await fetch('http://localhost:8080/api/ui/mappings/save', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify(configForBackend)
                });

                let batchConfigId = '';
                if (batchResponse.ok) {
                    batchConfigId = await batchResponse.text();
                    console.log('✅ Batch configuration saved! ID:', batchConfigId);
                } else {
                    console.warn('⚠️ Batch configuration save failed, proceeding with template-source mappings');
                }

                // Step 3B: Save template-source field mappings (US002 new functionality)
                const fieldMappings: FieldMapping[] = enhancedFields.map((field: any) => ({
                    targetFieldName: field.fieldName,
                    sourceFieldName: field.sourceField || '',
                    transformationType: field.transformationType || 'source',
                    transformationConfig: field.transformationConfig,
                    targetPosition: field.targetPosition,
                    length: field.length,
                    dataType: field.dataType
                }));

                const templateMappingRequest: TemplateSourceMappingRequest = {
                    fileType: selectedFileType,
                    transactionType: selectedTransactionType,
                    sourceSystemId: selectedSourceSystemId,
                    jobName: jobName,
                    fieldMappings: fieldMappings,
                    createdBy: 'template-user'
                };

                console.log('📋 Saving template-source field mappings:', templateMappingRequest);
                
                const mappingResponse = await templateSourceMappingApiService.saveTemplateSourceMapping(templateMappingRequest);
                console.log('✅ Template-source mappings saved successfully:', mappingResponse);

                // Success with both saves
                setActiveStep(2);
                const { templateMetadata } = configWithMetadata;
                const successMessage = `✅ Configuration saved successfully!

Template: ${templateMetadata.fileType}/${templateMetadata.transactionType}
Source System: ${selectedSourceSystemName}
Job Name: ${jobName}
Batch Config ID: ${batchConfigId || 'N/A'}
Field Mappings: ${mappingResponse.mappingCount} saved

🎉 Enhanced configuration saved to database!`;

                setSuccess(successMessage);
                setError(null);
                
            } catch (mappingError) {
                console.warn('⚠️ Template-source mapping save failed:', mappingError);
                // Still show success for batch configuration if it worked
                setActiveStep(2);
                const { templateMetadata } = configWithMetadata;
                const successMessage = `✅ Template configuration generated successfully!

Template: ${templateMetadata.fileType}/${templateMetadata.transactionType}
Source System: ${selectedSourceSystemName}
Job Name: ${jobName}
Fields prepared: ${enhancedFields.length}

📋 Note: Template-source field mappings could not be saved (${mappingError instanceof Error ? mappingError.message : 'Unknown error'})
💡 Configuration generation was successful - field mappings can be configured later.`;

                setSuccess(successMessage);
                setError(null);
            }

        } catch (error) {
            console.error('❌ Configuration generation failed:', error);
            
            const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
            setError(`Failed to generate configuration: ${errorMessage}`);
            setActiveStep(1);
            
        } finally {
            setLoading(false);
            console.log('🏁 Configuration generation process completed');
        }
    };

    const navigateToManualConfig = () => {
        if (selectedSourceSystemId && templateJobName) {
            navigate(`/configuration/${selectedSourceSystemId}/${templateJobName}`);
        }
    };

    const copyConfigToClipboard = () => {
        if (generatedConfig) {
            const configText = JSON.stringify(generatedConfig, null, 2);
            navigator.clipboard.writeText(configText).then(() => {
                alert('Configuration copied to clipboard!');
            }).catch(() => {
                alert('Failed to copy to clipboard');
            });
        }
    };

    return (
        <Container maxWidth="xl" sx={{ py: 3 }}>
            <Typography variant="h4" gutterBottom sx={{ color: 'primary.main', mb: 3 }}>
                Template-Based Configuration
            </Typography>

            {/* Stepper */}
            <Paper sx={{ p: 2, mb: 3 }}>
                <Stepper activeStep={activeStep} alternativeLabel>
                    {steps.map((label) => (
                        <Step key={label}>
                            <StepLabel>{label}</StepLabel>
                        </Step>
                    ))}
                </Stepper>
            </Paper>

            {/* Error Alert */}
            {error && (
                <Alert
                    severity="error"
                    sx={{ mb: 3 }}
                    onClose={() => setError(null)}
                    action={
                        <Button color="inherit" size="small" onClick={() => setError(null)}>
                            DISMISS
                        </Button>
                    }
                >
                    <Typography variant="body2">
                        <strong>Error:</strong> {error}
                    </Typography>
                    <Typography variant="caption" sx={{ mt: 1, display: 'block' }}>
                        Check the browser console for detailed error information.
                    </Typography>
                </Alert>
            )}

            {/* Success Alert */}
            {success && (
                <Alert
                    severity="success"
                    sx={{ mb: 3 }}
                    onClose={() => setSuccess(null)}
                    action={
                        <Box sx={{ display: 'flex', gap: 1 }}>
                            {generatedConfig && (
                                <>
                                    <Button 
                                        color="inherit" 
                                        size="small" 
                                        onClick={navigateToManualConfig}
                                        startIcon={<OpenInNew />}
                                    >
                                        Navigate to Manual Config
                                    </Button>
                                    <Button 
                                        color="inherit" 
                                        size="small" 
                                        onClick={copyConfigToClipboard}
                                    >
                                        Copy Config
                                    </Button>
                                </>
                            )}
                            <Button color="inherit" size="small" onClick={() => setSuccess(null)}>
                                DISMISS
                            </Button>
                        </Box>
                    }
                >
                    <Typography variant="body2" sx={{ whiteSpace: 'pre-line' }}>
                        {success}
                    </Typography>
                </Alert>
            )}

            {/* Step 1: Template Selection */}
            <Card sx={{ mb: 3 }}>
                <CardContent>
                    <Typography variant="h6" gutterBottom sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                        <Settings /> 1. Select Template
                    </Typography>

                    <Grid container spacing={2}>
                        <Grid item xs={12} md={3}>
                            <FormControl fullWidth>
                                <InputLabel>File Type</InputLabel>
                                <Select
                                    value={selectedFileType}
                                    onChange={(e) => setSelectedFileType(e.target.value)}
                                    label="File Type"
                                    disabled={loading}
                                >
                                    {fileTypes.map((ft) => (
                                        <MenuItem key={ft.fileType} value={ft.fileType}>
                                            {ft.fileType} - {ft.description}
                                        </MenuItem>
                                    ))}
                                </Select>
                            </FormControl>
                        </Grid>

                        <Grid item xs={12} md={3}>
                            <FormControl fullWidth>
                                <InputLabel>Transaction Type</InputLabel>
                                <Select
                                    value={selectedTransactionType}
                                    onChange={(e) => setSelectedTransactionType(e.target.value)}
                                    label="Transaction Type"
                                    disabled={!selectedFileType || loading}
                                >
                                    {transactionTypes.map((tt) => (
                                        <MenuItem key={tt} value={tt}>
                                            {tt}
                                        </MenuItem>
                                    ))}
                                </Select>
                            </FormControl>
                        </Grid>

                        {/* US002: Enhanced Source System Selection */}
                        <Grid item xs={12} md={4}>
                            <FormControl fullWidth>
                                <InputLabel>Source System</InputLabel>
                                <Select
                                    value={selectedSourceSystemId}
                                    onChange={handleSourceSystemChange}
                                    label="Source System"
                                    disabled={loadingSourceSystems || !selectedFileType || !selectedTransactionType}
                                >
                                    {availableSourceSystems.map((system) => (
                                        <MenuItem key={system.id} value={system.id}>
                                            <Box sx={{ display: 'flex', justifyContent: 'space-between', width: '100%', alignItems: 'center' }}>
                                                <Box>
                                                    <Typography variant="body2">{system.name}</Typography>
                                                    <Typography variant="caption" color="text.secondary">
                                                        {system.type} • {system.jobCount || 0} jobs
                                                    </Typography>
                                                </Box>
                                                {system.hasExistingConfiguration && (
                                                    <Chip size="small" label="Configured" color="success" />
                                                )}
                                            </Box>
                                        </MenuItem>
                                    ))}
                                </Select>
                                {loadingSourceSystems && (
                                    <Typography variant="caption" color="text.secondary" sx={{ mt: 0.5 }}>
                                        Loading source systems...
                                    </Typography>
                                )}
                            </FormControl>
                        </Grid>

                        {/* US002: Add New Source System Button */}
                        <Grid item xs={12} md={2}>
                            <Button
                                variant="outlined"
                                startIcon={<Add />}
                                onClick={() => setShowAddSourceSystemModal(true)}
                                sx={{ height: '56px', width: '100%' }}
                                disabled={loadingSourceSystems}
                            >
                                Add New System
                            </Button>
                        </Grid>

                        <Grid item xs={12} md={3}>
                            <TextField
                                fullWidth
                                size="small"
                                label="Job Name"
                                value={templateJobName}
                                onChange={(e) => setTemplateJobName(e.target.value)}
                                disabled={!selectedFileType || !selectedTransactionType}
                                helperText={
                                    selectedFileType && selectedTransactionType
                                        ? "Auto-generated from template (editable)"
                                        : "Select template to generate job name"
                                }
                            />
                        </Grid>
                    </Grid>

                    {selectedFileType && selectedTransactionType && templateJobName && selectedSourceSystemName && (
                        <Box sx={{ mt: 2, p: 2, bgcolor: 'primary.main', color: 'primary.contrastText', borderRadius: 1 }}>
                            <Typography variant="body2">
                                ✓ Selected: {selectedFileType} - {selectedTransactionType} • Source: {selectedSourceSystemName} → Job: {templateJobName}
                            </Typography>
                        </Box>
                    )}
                </CardContent>
            </Card>

            {/* Step 2: Template Fields */}
            {selectedFileType && selectedTransactionType && (
                <Card sx={{ mb: 3 }}>
                    <CardContent>
                        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
                            <Box>
                                <Typography variant="h6">
                                    2. Configure Field Mappings
                                    {selectedSourceSystemName && (
                                        <Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>
                                            Mapping {selectedFileType}/{selectedTransactionType} template to {selectedSourceSystemName}
                                        </Typography>
                                    )}
                                </Typography>
                            </Box>
                            <Chip
                                label={`${templateFields.length} fields`}
                                color="primary"
                                variant="outlined"
                            />
                        </Box>

                        <Alert severity="info" sx={{ mb: 2 }}>
                            {selectedSourceSystemName ? (
                                <>Target structure is from {selectedFileType} template. Map source fields from {selectedSourceSystemName} system and set transformation logic.</>
                            ) : (
                                <>Target structure is pre-configured from template. Select a source system above to enable field mapping.</>
                            )}
                        </Alert>

                        {loading ? (
                            <Box sx={{ display: 'flex', justifyContent: 'center', p: 3 }}>
                                <CircularProgress />
                            </Box>
                        ) : (
                            <Box sx={{ overflowX: 'auto' }}>
                                <Table size="small">
                                    <TableHead>
                                        <TableRow>
                                            <TableCell>Position</TableCell>
                                            <TableCell>Target Field</TableCell>
                                            <TableCell>Length</TableCell>
                                            <TableCell>Data Type</TableCell>
                                            <TableCell>Format</TableCell>
                                            <TableCell>Source Field ({selectedSourceSystemName || 'Source System'})</TableCell>
                                            <TableCell>Transformation</TableCell>
                                            <TableCell>Preview</TableCell>
                                        </TableRow>
                                    </TableHead>
                                    <TableBody>
                                        {templateFields.map((field, index) => (
                                            <TableRow key={field.fieldName} hover>
                                                <TableCell align="center">
                                                    <Chip size="small" label={field.targetPosition} />
                                                </TableCell>
                                                <TableCell>
                                                    <Typography variant="body2" fontWeight="bold">
                                                        {field.fieldName}
                                                    </Typography>
                                                    {field.required === 'Y' && (
                                                        <Chip size="small" label="Required" color="error" sx={{ ml: 1 }} />
                                                    )}
                                                </TableCell>
                                                <TableCell>{field.length}</TableCell>
                                                <TableCell>
                                                    <Chip size="small" label={field.dataType} variant="outlined" />
                                                </TableCell>
                                                <TableCell>{field.format || '-'}</TableCell>
                                                <TableCell>
                                                    <TextField
                                                        size="small"
                                                        placeholder={selectedSourceSystemName ? `Source field from ${selectedSourceSystemName}` : "Select source system first"}
                                                        value={field.sourceField || ''}
                                                        onChange={(e) => handleSourceFieldChange(index, e.target.value)}
                                                        disabled={!selectedSourceSystemId}
                                                        sx={{ width: 200 }}
                                                        helperText={selectedSourceSystemId && field.sourceField ? `${field.sourceField} → ${field.fieldName}` : ''}
                                                    />
                                                </TableCell>
                                                <TableCell>
                                                    <Select
                                                        size="small"
                                                        value={field.transformationType || 'source'}
                                                        onChange={(e) => handleTransformationChange(index, e.target.value)}
                                                        disabled={!selectedSourceSystemId}
                                                        sx={{ width: 140 }}
                                                    >
                                                        <MenuItem value="source">Direct Mapping</MenuItem>
                                                        <MenuItem value="constant">Constant Value</MenuItem>
                                                        <MenuItem value="formula">Formula/Expression</MenuItem>
                                                        <MenuItem value="lookup">Lookup Table</MenuItem>
                                                        <MenuItem value="conditional">Conditional Logic</MenuItem>
                                                    </Select>
                                                </TableCell>
                                                <TableCell>
                                                    {/* US002: Preview mapping result */}
                                                    <Chip 
                                                        size="small" 
                                                        label={
                                                            field.sourceField && selectedSourceSystemId ? 
                                                                `${field.sourceField} → ${field.fieldName}` : 
                                                                'Not mapped'
                                                        }
                                                        color={
                                                            field.sourceField && selectedSourceSystemId ? 
                                                                'success' : 
                                                                'default'
                                                        }
                                                        variant={field.sourceField && selectedSourceSystemId ? 'filled' : 'outlined'}
                                                    />
                                                </TableCell>
                                            </TableRow>
                                        ))}
                                    </TableBody>
                                </Table>
                            </Box>
                        )}
                    </CardContent>
                </Card>
            )}

            {/* Step 3: Actions */}
            {templateFields.length > 0 && (
                <Card>
                    <CardContent>
                        <Typography variant="h6" gutterBottom>
                            3. Generate Configuration
                        </Typography>

                        <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap' }}>
                            <Button
                                variant="contained"
                                startIcon={loading ? <CircularProgress size={20} /> : <Save />}
                                onClick={generateConfiguration}
                                disabled={loading || !selectedSourceSystemId || !templateJobName}
                            >
                                Generate & Save Configuration
                            </Button>

                            <Button
                                variant="outlined"
                                startIcon={<Download />}
                                disabled={loading}
                            >
                                Export Template
                            </Button>

                            <Button
                                variant="outlined"
                                startIcon={<Upload />}
                                disabled={loading}
                            >
                                Import Mappings
                            </Button>
                        </Box>

                        {(!selectedSourceSystemId || !templateJobName) && (
                            <Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>
                                {!selectedSourceSystemId
                                    ? "Please select a source system from the dropdown."
                                    : "Please select a template to generate a job name."
                                }
                            </Typography>
                        )}
                    </CardContent>
                </Card>
            )}

            {/* Generated Configuration Display */}
            {generatedConfig && activeStep === 2 && (
                <Card sx={{ mt: 3 }}>
                    <CardContent>
                        <Typography variant="h6" gutterBottom>
                            Generated Configuration Summary
                        </Typography>
                        
                        <Box sx={{ bgcolor: 'grey.100', p: 2, borderRadius: 1, mb: 2 }}>
                            <Typography variant="body2">
                                <strong>Job:</strong> {generatedConfig.jobName}<br/>
                                <strong>Source System:</strong> {generatedConfig.sourceSystem}<br/>
                                <strong>Transaction Type:</strong> {generatedConfig.transactionType}<br/>
                                <strong>Fields:</strong> {generatedConfig.fields?.length || 0}
                            </Typography>
                        </Box>

                        <Typography variant="subtitle2" gutterBottom>
                            Field Mappings:
                        </Typography>
                        
                        {generatedConfig.fields?.slice(0, 5).map((field: any, index: number) => (
                            <Typography key={index} variant="body2" sx={{ fontFamily: 'monospace', fontSize: '0.8rem' }}>
                                {field.targetPosition}. {field.fieldName} → {field.sourceField || '(no source)'} 
                                ({field.transformationType})
                            </Typography>
                        ))}
                        
                        {generatedConfig.fields?.length > 5 && (
                            <Typography variant="body2" color="text.secondary">
                                ... and {generatedConfig.fields.length - 5} more fields
                            </Typography>
                        )}
                    </CardContent>
                </Card>
            )}

            {/* US002: Add New Source System Modal */}
            <AddSourceSystemModal
                open={showAddSourceSystemModal}
                onClose={() => setShowAddSourceSystemModal(false)}
                onSourceSystemCreated={handleNewSourceSystemCreated}
            />
        </Container>
    );
};

export default TemplateConfigurationPage;